# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(email: 'ssales@itpm-gk.com', password: 'mmiyatateruo', role: 0)
User.create!(email: 'sales@itpm-gk.com', password: 'miyatateruo', role: 1)
User.create!(email: 'all@itpm-gk.com', password: 'iittppmm', role: 2)
Field.create!(id: 1, name: 'アプリ開発')
Field.create!(id: 2, name: 'データベース')
Field.create!(id: 3, name: 'インフラ')
Field.create!(id: 4, name: 'サービスマネジメント')
Field.create!(id: 5, name: 'PMO')
Field.create!(id: 6, name: 'WEBディレクター')
Field.create!(id: 7, name: 'WEBデザイナー')
Field.create!(id: 8, name: 'マークアップエンジニア')
Levelname.create!(id: 1, code: 5 ,name: 'Level 5')
Levelname.create!(id: 2, code: 4 ,name: 'Level 4')
Levelname.create!(id: 3, code: 3 ,name: 'Level 3')
Levelname.create!(id: 4, code: 2 ,name: 'Level 2')
Levelname.create!(id: 5, code: 1 ,name: 'Level 1')
Levelname.create!(id: 6, code: 0 ,name: 'エントリー')
Levelname.create!(id: 7, code: -1,name: 'トレーニング')
Level.create!(field_id: 1, mintariff: 100, maxtariff: 120, name: "", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 1, mintariff: 70, maxtariff: 100, name: "上級SE\r\n（工程： 要件定義）", skill: "・顧客と要件をすり合わせ、要件定義書を作成できる", tool: "Java,PHP、C#、", certificate: "", levelname_id: 2)
Level.create!(field_id: 1, mintariff: 60, maxtariff: 80, name: "SE\r\n（工程： 基本設計）", skill: "・要件定義書を元に、基本設計書を作成できる", tool: "", certificate: "", levelname_id: 3)
Level.create!(field_id: 1, mintariff: 50, maxtariff: 70, name: "PG\r\n（工程： 詳細設計、製造）\r\n新規開発、保守\r\n", skill: "・基本設計書を元に、詳細設計書を作成できる", tool: "", certificate: "", levelname_id: 4)
Level.create!(field_id: 1, mintariff: 40, maxtariff: 50, name: "PG\r\n（工程： 詳細設計、製造、テストケース作成）\r\n改修、保守\r\n", skill: "・詳細設計書に従ってコーディングができる\r\n・単体テスト、結合テストができる", tool: "Access VBA、Excel VBA", certificate: "", levelname_id: 5)
Level.create!(field_id: 1, mintariff: 35, maxtariff: 40, name: "ジュニアPG\r\n（工程： テスト）", skill: "・テストケースに従ってテストができる\r\n・画面のエビデンスを取得できる\r\n・バグが生じた際は適切なエスカレーションができる", tool: "", certificate: "", levelname_id: 6)
Level.create!(field_id: 1, mintariff: 0, maxtariff: 0, name: "アプリ開発基礎", skill: "", tool: "", certificate: "", levelname_id: 7)
Level.create!(field_id: 2, mintariff: 100, maxtariff: 120, name: "", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 2, mintariff: 70, maxtariff: 100, name: "上級SE\r\n（工程： 要件定義）", skill: "・業務データの分析・モデリングを行いER図を作成する。\r\n・今後のデータ増加量予想や過去データ削除ルールなど\r\n　を考慮して必要なディスク容量を見積もる。", tool: "", certificate: "・ITストラテジスト\r\n・データベーススペシャリスト", levelname_id: 2)
Level.create!(field_id: 2, mintariff: 60, maxtariff: 80, name: "SE\r\n（工程： 基本設計）", skill: "・ER図に基づき、スキーマ, テーブル, インデックスの\r\n　設計を行う。必要に応じてテーブルの正規化を見直す。\r\n・システム要件に応じてクラスタ, レプリ\r\nケーションの\r\n　設計を行う。\r\n・DBアカウントごとに適切な権限を決定する。\r\n", tool: "Oracle, PostgreSQL, MySQL", certificate: "・データベーススペシャリスト\r\n・Oracle Master", levelname_id: 3)
Level.create!(field_id: 2, mintariff: 50, maxtariff: 70, name: "SE\r\n（工程： 詳細設計、構築、テスト）", skill: "・基本設計に基づきDBをインストールし、スキーマ,\r\n　テーブル, インデックス, アカウント作成や、クラスタ,\r\n　レプリケーションの設定を行う。\r\n・初期データのロードを行う。\r\n・パフォーマンスチューニングを行う。\r\n・バックアップ／リカバリテストを行う。", tool: "（同上）", certificate: "・Oracle Master", levelname_id: 4)
Level.create!(field_id: 2, mintariff: 40, maxtariff: 50, name: "", skill: "", tool: "", certificate: "", levelname_id: 5)
Level.create!(field_id: 2, mintariff: 35, maxtariff: 40, name: "", skill: "", tool: "", certificate: "", levelname_id: 6)
Level.create!(field_id: 2, mintariff: 0, maxtariff: 0, name: "", skill: "", tool: "", certificate: "", levelname_id: 7)
Level.create!(field_id: 3, mintariff: 100, maxtariff: 120, name: "", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 3, mintariff: 70, maxtariff: 100, name: "上級SE\r\n（工程： 要件定義）", skill: "・顧客のニーズをヒアリングし、業務分析を行い、\r\n　システムとして必要な機能を洗い出す。\r\n・業務機能だけではなく、レスポンス要件(各処理の\r\n　許容時間)、バックアップ／リストア計画(データ\r\n　障害時に「どの時点」に「いつまでに」戻すか)、\r\n　セキュリティポリシー、データ量見積なども盛り込む。\r\n", tool: "", certificate: "・ITストラテジスト", levelname_id: 2)
Level.create!(field_id: 3, mintariff: 60, maxtariff: 80, name: "SE\r\n（工程： 基本設計）", skill: "・要件定義を実現するために、サーバ構成を設計する。\r\n　(OS、ミドルウェア、ツール、DB、CPU・メモリなどの\r\n　ハード要件、台数、クラスタ化の有無、ストレージの\r\n　容量、など)\r\n・ネットワーク設計(セグメント分割やIPアドレス体系)を\r\n　行う。\r\n", tool: "Linux, Windows, vSphere, Apache,\r\nTomcat, Oracle, PostgreSQL,\r\nMySQL, JP/1, Zabbix, Data\r\nProtector, NetValut、など", certificate: "・システムアーキテクト", levelname_id: 3)
Level.create!(field_id: 3, mintariff: 50, maxtariff: 70, name: "SE\r\n（工程： 詳細設計、構築、テスト）", skill: "・基本設計に基づきOSやミドルウェアの具体的な設定値\r\n　を設計する。(サーバ間の通信要件なども含む)\r\n・OS、ミドルウェア、DB、ツールをインストールし、動作\r\n　確認を行う。\r\n・テスト計画書を作成し、要件定義を満たしているか\r\n　テストを行う。（単体テスト、結合テスト、システム\r\n　テスト、障害テストなど。ネットワークチーム、アプリ\r\n　チーム、運用テームとの連携テストもあり)\r\n・サーバ, アプリ, ネットワーク監視やバックアップなどの\r\n　運用設計もこのフェーズに含まれる。", tool: "（同上）", certificate: "・LPIC\r\n・MCP\r\n・Oracle Master\r\n・CCNP, CCNA", levelname_id: 4)
Level.create!(field_id: 3, mintariff: 40, maxtariff: 50, name: "SE\r\n（工程： システム運用／保守）", skill: "・運用設計書を元に具体的な運用手順書を作成する。\r\n・運用手順書に基づき、運用・保守作業を行う。(障害\r\n　対応を含む)", tool: "JP/1, Zabbix、など", certificate: "・LPIC, MCP\r\n・応用・基本情報技術者, ITパスポート", levelname_id: 5)
Level.create!(field_id: 3, mintariff: 35, maxtariff: 40, name: "ジュニアSE\r\n（工程： システム監視、オペレーション）", skill: "・運用手順書に基づき、監視・運用ができる。\r\n・スクリーンショットなど適切なエビデンスを取得できる。\r\n・障害発生時に手順通りに行動できる。", tool: "（同上）", certificate: "（同上）", levelname_id: 6)
Level.create!(field_id: 3, mintariff: 0, maxtariff: 0, name: "インフラ基礎", skill: "", tool: "", certificate: "", levelname_id: 7)
Level.create!(field_id: 4, mintariff: 100, maxtariff: 120, name: "コンサルタント\r\n（CIO、IT戦略）", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 4, mintariff: 70, maxtariff: 100, name: "上級サービスマネージャ\r\n（IT企画、設計）", skill: "", tool: "", certificate: "", levelname_id: 2)
Level.create!(field_id: 4, mintariff: 60, maxtariff: 80, name: "サービスマネージャ\r\n（IT運用設計）", skill: "", tool: "", certificate: "", levelname_id: 3)
Level.create!(field_id: 4, mintariff: 50, maxtariff: 70, name: "上級ヘルプデスク\r\n（SV）\r\nマネジメント", skill: "・二次対応で解決仕切れない問題の解決を行う\r\n・ヘルプデスク対応の取りまとめ、改善点の提案等を行う\r\n・ヘルプデスク要員管理、教育", tool: "・ヘルプデスク統括\r\n", certificate: "・MCP\r\n・応用・基本情報技術者\r\n・P検　1級,2級\r\n・CompTIA Server+,Network+,Security+", levelname_id: 4)
Level.create!(field_id: 4, mintariff: 40, maxtariff: 50, name: "ヘルプデスク\r\n（非定型作業）\r\nトラブル対応", skill: "・一次対応で解決仕切れない高度な問題の解決が行える。\r\n・他部署・ユーザとの調整交渉が行える\r\n・業務マニュアル（手順書）の作成\r\n・新規導入機器の検証業務\r\n", tool: "・ヘルプデスク（二次対応）\r\n", certificate: "・MCP\r\n・応用・基本情報技術者, ITパスポート\r\n・P検　2級\r\n・CompTIA A+", levelname_id: 5)
Level.create!(field_id: 4, mintariff: 35, maxtariff: 40, name: "ヘルプデスク\r\n（定型作業）\r\nアカウント管理、PCキッティング", skill: "・電話、メール、対面による障害の受付、簡単な問題の解決が行える。\r\n・業務マニュアル（手順書）を元に基本的なPCキッティングが行える", tool: "・ヘルプデスク（一次対応）\r\n　障害の受付と問題切り分け、簡単な問題の解決", certificate: "・P検　準2級\r\n・ITパスポート\r\n・CompTIA IT Fundamentals", levelname_id: 6)
Level.create!(field_id: 4, mintariff: 0, maxtariff: 0, name: "", skill: "", tool: "", certificate: "", levelname_id: 7)
Level.create!(field_id: 5, mintariff: 100, maxtariff: 120, name: "上級プロジェクトマネージャ\r\n（大規模システム開発）", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 5, mintariff: 70, maxtariff: 100, name: "プロジェクトマネージャ", skill: "", tool: "", certificate: "", levelname_id: 2)
Level.create!(field_id: 5, mintariff: 60, maxtariff: 80, name: "上級PMO", skill: "計画策定：ゼロベースで作成でき、プロジェクト内で調整することができる\r\n進捗管理プロセス策定：ゼロベースで作成でき、かつ作業指示を明確にすることができる。\r\n進捗の集計：進捗の予実比較ができる。その結果の問題整理をし、解決アクションができる\r\n進捗レポートの作成：定型レポートの作業指示を行え、マネジメント層へのアドバイスができる\r\n進捗会議：議事進行をしながら議事録を作成、指摘ができる\r\n進捗の把握：リカバリプランの策定と実施", tool: "プロジェクトマネージャーの黒子\r\n（PM補佐、サブPM）\r\n※プロジェクトマネージャーとの違いは、\r\n人事権限を持たない、予算権限を持たない", certificate: "", levelname_id: 3)
Level.create!(field_id: 5, mintariff: 50, maxtariff: 70, name: "PMO", skill: "計画策定：サンプルを活用しながら作成できる\r\n進捗管理プロセス策定：ゼロベースで作成でき、プロジェクトメンバーへの定着化までできる\r\n進捗の集計：進捗報告を催促し、遅れているチームへの是正、定型チェックポイントおよび独自チェックポイントの策定ができる\r\n進捗レポートの作成：マネジメントの意志決定に寄与するレポートを作成できる\r\n進捗会議：必要なメンバーの判断、資料の準備ができる\r\n\r\n議事録の作成（24時間以内の提出）\r\n進捗の把握：遅延状況のヒアリング", tool: "プロジェクトの可視化ができる人", certificate: "", levelname_id: 4)
Level.create!(field_id: 5, mintariff: 40, maxtariff: 50, name: "ジュニアPMO", skill: "計画策定：上司の指示により作成できる\r\n進捗管理プロセス策定：サンプルを活用しながら作成できる\r\n進捗の集計：進捗報告を催促し、遅れているチームへの是正、定型チェックポイントの策定ができる\r\n進捗レポートの作成：定型的なレポートの作成ができる\r\n進捗会議：必要なメンバーの判断ができる\r\n\r\n録音した議事録を要約録形式の議事録に起こすことができる\r\n進捗の把握：（対策は打てない）", tool: "細々したことをテキパキやってくれる人", certificate: "", levelname_id: 5)
Level.create!(field_id: 5, mintariff: 35, maxtariff: 40, name: "IT事務", skill: "", tool: "各種手続き\r\n・メンバー管理（セキュリティ、入退出）\r\n・成果物管理", certificate: "", levelname_id: 6)
Level.create!(field_id: 5, mintariff: 0, maxtariff: 0, name: "", skill: "", tool: "", certificate: "", levelname_id: 7)
Level.create!(field_id: 6, mintariff: 100, maxtariff: 120, name: "", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 6, mintariff: 70, maxtariff: 100, name: "", skill: "", tool: "", certificate: "", levelname_id: 2)
Level.create!(field_id: 6, mintariff: 60, maxtariff: 80, name: "上級ディレクター", skill: "・開発部隊とも連携できる（開発言語知識）\r\n・プロジェクトの企画立案ができる\r\n・競合他社サイトを分析できる", tool: "Java, PHP, Ruby", certificate: "", levelname_id: 3)
Level.create!(field_id: 6, mintariff: 50, maxtariff: 70, name: "ディレクター", skill: "・中小規模の制作ディレクション（進捗管理、指示だし）ができる\r\n・A/Bテストやアクセス解析を通じてPDCAを回せる\r\n・顧客対応、部署間調整ができる", tool: "Adobe Analytics\r\nOptimizely, Kaizen Platform, Visual Website Optimizer", certificate: "上級ウェブ解析士\r\nGAIQ\r\nGoogle AdWords認定資格", levelname_id: 4)
Level.create!(field_id: 6, mintariff: 40, maxtariff: 50, name: "ジュニアディレクター", skill: "・基礎的なコーディング、デザイン知識がある\r\n・ディレクターの下で補佐ができる\r\n・資料作成ができる\r\n・WEB解析ツールの使い方を知っている", tool: "HTML5, CSS3\r\nPhotoshop, Illustrator\r\nWord、Excel、PowerPoint\r\nGoogle Analytics", certificate: "", levelname_id: 5)
Level.create!(field_id: 6, mintariff: 35, maxtariff: 40, name: "", skill: "", tool: "", certificate: "", levelname_id: 6)
Level.create!(field_id: 6, mintariff: 0, maxtariff: 0, name: "", skill: "", tool: "", certificate: "", levelname_id: 7)
Level.create!(field_id: 7, mintariff: 100, maxtariff: 120, name: "", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 7, mintariff: 70, maxtariff: 100, name: "", skill: "", tool: "", certificate: "", levelname_id: 2)
Level.create!(field_id: 7, mintariff: 60, maxtariff: 80, name: "", skill: "", tool: "", certificate: "", levelname_id: 3)
Level.create!(field_id: 7, mintariff: 50, maxtariff: 70, name: "上級デザイナー", skill: "・大規模サイトのデザイン（ワイヤー、モック）ができる\r\n　　※大規模サイト→10000PV/日レベル\r\n・A/Bテストやアクセス解析を通じてUI/UXの改善できる", tool: "", certificate: "", levelname_id: 4)
Level.create!(field_id: 7, mintariff: 40, maxtariff: 50, name: "デザイナー", skill: "・中規模サイトのデザイン（ワイヤー、モック）ができる\r\n・コーダーと連携できる（HTML, CSS, JSの基礎知識がある）", tool: "HTML5, CSS3, Javascript", certificate: "", levelname_id: 5)
Level.create!(field_id: 7, mintariff: 35, maxtariff: 40, name: "ジュニアデザイナー", skill: "・小規模サイトデザイン（ワイヤー、モック作成）ができる\r\n　※小規模サイト：LPや中小企業HPなど\r\n・キャラクターデザインができる\r\n・バナー作成ができる\r\n・ロゴ、ボタン等の素材が作成できる", tool: "", certificate: "", levelname_id: 6)
Level.create!(field_id: 7, mintariff: 0, maxtariff: 0, name: "デザイナー基礎", skill: "・Photoshop, Illustratorを使用できる", tool: "Photoshop, Illustrator", certificate: "", levelname_id: 7)
Level.create!(field_id: 8, mintariff: 100, maxtariff: 120, name: "", skill: "", tool: "", certificate: "", levelname_id: 1)
Level.create!(field_id: 8, mintariff: 70, maxtariff: 100, name: "", skill: "", tool: "", certificate: "", levelname_id: 2)
Level.create!(field_id: 8, mintariff: 60, maxtariff: 80, name: "", skill: "", tool: "", certificate: "", levelname_id: 3)
Level.create!(field_id: 8, mintariff: 50, maxtariff: 70, name: "上級コーダー", skill: "・バックエンド言語の知見がある\r\n・JSの最新技術の知見がある\r\n・SEOの最新情報の知見がある", tool: "Java, PHP, Ruby", certificate: "", levelname_id: 4)
Level.create!(field_id: 8, mintariff: 40, maxtariff: 50, name: "コーダー", skill: "・JavaScript開発が可能\r\n・各種JSフレームワークの知見がある\r\n・CSS設計概念（再利用性）がある\r\n・SEOに準拠したコーディングができる", tool: "Javascript\r\nReact、Backbone、Angular", certificate: "", levelname_id: 5)
Level.create!(field_id: 8, mintariff: 35, maxtariff: 40, name: "ジュニアコーダー", skill: "・デザイン案（ワイヤー、モック）からコーディングできる\r\n・Jqueryを利用できる", tool: "", certificate: "", levelname_id: 6)
Level.create!(field_id: 8, mintariff: 0, maxtariff: 0, name: "コーダー基礎", skill: "・HTML,CSSを使用できる", tool: "HTML5, CSS3,", certificate: "", levelname_id: 7)
